name: Syntax Tests

on:
  push:
    paths:
      - '**/syntax_test_*'
      - '**/*.sublime-syntax'
      - '.github/workflows/main.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**/syntax_test_*'
      - '**/*.sublime-syntax'
      - '.github/workflows/main.yml'
  workflow_dispatch:

jobs:
  run_syntax_tests:
    name: Test on Build ${{ matrix.sublime-build }} (${{ matrix.sublime-channel }})
    runs-on: ubuntu-latest
    timeout-minutes: 5
    continue-on-error: ${{ matrix.optional }}
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        include:
          - sublime-channel: stable
            sublime-build: 4126
            optional: false
    steps:

      - name: Git checkout
        uses: actions/checkout@master

      - name: Get binary for Build ${{ matrix.sublime-build }} (${{ matrix.sublime-channel }})
        run: |
          wget -O st_syntax_tests.tar.xz https://download.sublimetext.com/st_syntax_tests_build_${{ matrix.sublime-build }}_x64.tar.xz
          tar xf st_syntax_tests.tar.xz
          rm -R st_syntax_tests.tar.xz

      - name: 'Move package contents into "Data/Packages/PureBasic"'
        run: |
          mkdir -p st_syntax_tests/Data/Packages/PureBasic
          find . -mindepth 1 -maxdepth 1 -not -name '.' -not -path './st_syntax_tests*' -exec mv '{}' st_syntax_tests/Data/Packages/PureBasic ';'

      - name: Move everything into the working directory again
        run: |
          mv st_syntax_tests/* ./
          rm -R st_syntax_tests

      - name: Run syntax tests
        run: ./syntax_tests